In [89]:
# importing libraries 
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.impute import SimpleImputer
from sklearn.tree import DecisionTreeClassifier

In [90]:
# importing the titanic dataset 
df = pd.read_csv(r"C:\Skills\Machine Learning\ML main\Understanding Data\Titanic-Dataset.csv")

In [91]:
df.head()

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [92]:
# taking only columns that we will use for our model 
df = df.drop(columns=['PassengerId','Name','Ticket','Cabin'])

In [93]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [94]:
# Step 1 train test split 
x_train, x_test , y_train, y_test = train_test_split(df.iloc[:,1:],df['Survived'],test_size=0.2,random_state=42)

In [95]:
x_train.head()

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
331       1    male  45.5      0      0  28.5000        S
733       2    male  23.0      0      0  13.0000        S
382       3    male  32.0      0      0   7.9250        S
704       3    male  26.0      1      0   7.8542        S
813       3  female   6.0      4      2  31.2750        S

In [96]:
# firstly we will apply simple imputer to handle missing values 
si_age = SimpleImputer()
si_embarked = SimpleImputer(strategy='most_frequent')

In [97]:
x_train

     Pclass     Sex   Age  SibSp  Parch      Fare Embarked
331       1    male  45.5      0      0   28.5000        S
733       2    male  23.0      0      0   13.0000        S
382       3    male  32.0      0      0    7.9250        S
704       3    male  26.0      1      0    7.8542        S
813       3  female   6.0      4      2   31.2750        S
..      ...     ...   ...    ...    ...       ...      ...
106       3  female  21.0      0      0    7.6500        S
270       1    male   NaN      0      0   31.0000        S
860       3    male  41.0      2      0   14.1083        S
435       1  female  14.0      1      2  120.0000        S
102       1    male  21.0      0      1   77.2875        S

[712 rows x 7 columns]

In [98]:
x_train_age = si_age.fit_transform(x_train[['Age']])
x_train_embarked = si_embarked.fit_transform(x_train[['Embarked']])

x_test_age = si_age.transform(x_test[['Age']])
x_test_embarked = si_embarked.transform(x_test[['Embarked']])

In [99]:
# doing one hot encoding on categorical data
ohe_sex = OneHotEncoder(drop='first',sparse_output=False)
ohe_embarked = OneHotEncoder(drop='first',sparse_output=False)

x_train_sex = ohe_sex.fit_transform(x_train[['Sex']])
x_train_embarked = ohe_embarked.fit_transform(x_train_embarked)

x_test_sex = ohe_sex.transform(x_test[['Sex']])
x_test_embarked = ohe_embarked.transform(x_test_embarked)

In [100]:
x_test_rem

array([[  3.    ,   1.    ,   1.    ,  15.2458],
       [  2.    ,   0.    ,   0.    ,  10.5   ],
       [  3.    ,   0.    ,   0.    ,   7.925 ],
       [  2.    ,   0.    ,   1.    ,  33.    ],
       [  3.    ,   1.    ,   0.    ,  11.2417],
       [  1.    ,   0.    ,   0.    ,  78.85  ],
       [  3.    ,   0.    ,   0.    ,   7.75  ],
       [  3.    ,   2.    ,   0.    ,  18.    ],
       [  3.    ,   0.    ,   0.    ,   7.75  ],
       [  1.    ,   0.    ,   2.    ,  26.2833],
       [  1.    ,   1.    ,   0.    ,  53.1   ],
       [  3.    ,   0.    ,   0.    ,   8.05  ],
       [  3.    ,   3.    ,   1.    ,  25.4667],
       [  3.    ,   0.    ,   0.    ,   7.225 ],
       [  2.    ,   0.    ,   0.    ,  13.    ],
       [  1.    ,   0.    ,   1.    ,  39.4   ],
       [  1.    ,   1.    ,   0.    ,  52.5542],
       [  3.    ,   0.    ,   0.    ,   7.8292],
       [  2.    ,   0.    ,   0.    ,  13.    ],
       [  1.    ,   0.    ,   0.    ,  52.    ],
       [  3.    ,   0.    ,   0.    ,   7.8958],
       [  1.    ,   0.    ,   0.    ,  26.55  ],
       [  3.    ,   1.    ,   0.    ,   7.8542],
       [  3.    ,   0.    ,   0.    ,   9.225 ],
       [  3.    ,   0.    ,   0.    ,  14.5   ],
       [  3.    ,   3.    ,   2.    ,  27.9   ],
       [  1.    ,   0.    ,   0.    ,  27.7208],
       [  2.    ,   0.    ,   0.    ,  13.    ],
       [  3.    ,   3.    ,   2.    ,  27.9   ],
       [  3.    ,   0.    ,   0.    ,   7.8542],
       [  3.    ,   0.    ,   0.    ,   7.8958],
       [  3.    ,   0.    ,   0.    ,   7.75  ],
       [  1.    ,   0.    ,   0.    ,  30.6958],
       [  3.    ,   0.    ,   0.    ,   7.55  ],
       [  3.    ,   0.    ,   0.    ,   8.05  ],
       [  3.    ,   1.    ,   0.    ,  14.4542],
       [  1.    ,   0.    ,   0.    ,  35.5   ],
       [  3.    ,   0.    ,   0.    ,   7.75  ],
       [  1.    ,   0.    ,   0.    ,  31.    ],
       [  3.    ,   0.    ,   0.    ,   7.8958],
       [  2.    ,   2.    ,   0.    ,  73.5   ],
       [  3.    ,   1.    ,   0.    ,   7.0458],
       [  3.    ,   0.    ,   0.    ,   8.05  ],
       [  3.    ,   0.    ,   0.    ,   7.75  ],
       [  3.    ,   0.    ,   1.    ,  14.4542],
       [  3.    ,   1.    ,   3.    ,  34.375 ],
       [  3.    ,   0.    ,   0.    ,   8.1583],
       [  3.    ,   0.    ,   0.    ,   9.225 ],
       [  3.    ,   0.    ,   0.    ,   7.05  ],
       [  1.    ,   0.    ,   2.    , 113.275 ],
       [  3.    ,   2.    ,   1.    ,  19.2583],
       [  1.    ,   1.    ,   1.    ,  93.5   ],
       [  3.    ,   1.    ,   4.    ,  27.9   ],
       [  1.    ,   1.    ,   2.    , 120.    ],
       [  3.    ,   0.    ,   0.    ,   7.75  ],
       [  1.    ,   0.    ,   2.    ,  79.65  ],
       [  2.    ,   0.    ,   0.    ,  10.5   ],
       [  1.    ,   0.    ,   1.    , 247.5208],
       [  2.    ,   0.    ,   0.    ,  21.    ],
       [  3.    ,   0.    ,   0.    ,   7.8792],
       [  3.    ,   0.    ,   0.    ,   7.775 ],
       [  2.    ,   0.    ,   1.    ,  19.5   ],
       [  2.    ,   1.    ,   0.    ,  26.    ],
       [  1.    ,   0.    ,   0.    ,  25.925 ],
       [  3.    ,   0.    ,   0.    ,   7.75  ],
       [  2.    ,   0.    ,   0.    ,  10.5   ],
       [  2.    ,   0.    ,   0.    ,  73.5   ],
       [  3.    ,   0.    ,   0.    ,   7.875 ],
       [  3.    ,   1.    ,   1.    ,   7.2292],
       [  1.    ,   1.    ,   0.    ,  78.2667],
       [  2.    ,   1.    ,   1.    ,  26.    ],
       [  1.    ,   2.    ,   2.    , 262.375 ],
       [  1.    ,   0.    ,   0.    ,  30.    ],
       [  1.    ,   1.    ,   1.    ,  83.1583],
       [  3.    ,   0.    ,   0.    ,   7.8542],
       [  3.    ,   1.    ,   0.    ,  15.55  ],
       [  3.    ,   0.    ,   0.    ,   7.75  ],
       [  1.    ,   0.    ,   2.    ,  49.5   ],
       [  2.    ,   0.    ,   0.    ,  13.    ],
       [  3.    ,   0.    ,   2.    ,  20.2125],
       [  3.    ,   4.    ,   1.    ,  39.6875],
       [  2.    ,   0.    ,   0.    ,  10.5   ],
       [  1.    ,   1.    ,   1.    , 134.5   ],
       [  3.    ,   0.    ,   0.    ,   7.7375],
       [  1.    ,   0.    ,   0.    ,  30.6958],
       [  1.    ,   0.    ,   0.    ,  49.5042],
       [  1.    ,   1.    ,   0.    , 113.275 ],
       [  1.    ,   0.    ,   0.    ,  56.9292],
       [  1.    ,   0.    ,   0.    ,   0.    ],
       [  3.    ,   0.    ,   0.    ,   7.25  ],
       [  3.    ,   0.    ,   2.    ,  20.525 ],
       [  3.    ,   4.    ,   2.    ,  31.275 ],
       [  1.    ,   0.    ,   0.    ,  32.3208],
       [  3.    ,   0.    ,   0.    ,   7.7292],
       [  3.    ,   0.    ,   0.    ,   7.8958],
       [  3.    ,   0.    ,   0.    ,   7.8542],
       [  1.    ,   1.    ,   0.    ,  52.    ],
       [  3.    ,   0.    ,   0.    ,   8.05  ],
       [  2.    ,   0.    ,   0.    ,  13.    ],
       [  3.    ,   0.    ,   0.    ,   7.8958],
       [  1.    ,   0.    ,   0.    ,  26.    ],
       [  3.    ,   0.    ,   0.    ,   7.125 ],
       [  1.    ,   1.    ,   0.    ,  91.0792],
       [  3.    ,   0.    ,   0.    ,   7.05  ],
       [  3.    ,   0.    ,   0.    ,   8.05  ],
       [  3.    ,   1.    ,   0.    ,   7.775 ],
       [  2.    ,   1.    ,   1.    ,  39.    ],
       [  1.    ,   0.    ,   0.    ,  38.5   ],
       [  3.    ,   0.    ,   0.    ,   9.5   ],
       [  1.    ,   0.    ,   0.    ,  31.    ],
       [  1.    ,   1.    ,   0.    ,  52.    ],
       [  3.    ,   0.    ,   0.    ,   7.25  ],
       [  1.    ,   1.    ,   0.    ,  89.1042],
       [  1.    ,   0.    ,   0.    ,  26.2875],
       [  1.    ,   0.    ,   0.    , 221.7792],
       [  3.    ,   0.    ,   0.    ,   9.8458],
       [  1.    ,   0.    ,   0.    ,  34.6542],
       [  2.    ,   0.    ,   0.    ,  12.875 ],
       [  2.    ,   1.    ,   1.    ,  29.    ],
       [  3.    ,   1.    ,   3.    ,  34.375 ],
       [  2.    ,   2.    ,   1.    ,  11.5   ],
       [  1.    ,   0.    ,   0.    ,  76.2917],
       [  1.    ,   1.    ,   0.    ,  77.9583],
       [  2.    ,   0.    ,   2.    ,  29.    ],
       [  3.    ,   0.    ,   0.    ,   7.25  ],
       [  1.    ,   0.    ,   0.    ,  26.55  ],
       [  1.    ,   0.    ,   0.    ,  25.9292],
       [  1.    ,   0.    ,   0.    ,  79.2   ],
       [  3.    ,   1.    ,   0.    ,  14.4583],
       [  3.    ,   0.    ,   0.    ,   8.05  ],
       [  3.    ,   0.    ,   0.    ,   7.8792],
       [  3.    ,   1.    ,   1.    ,  15.2458],
       [  2.    ,   0.    ,   0.    ,   0.    ],
       [  3.    ,   0.    ,   0.    ,  12.475 ],
       [  1.    ,   1.    ,   0.    ,  56.9292],
       [  3.    ,   1.    ,   0.    ,  14.4542],
       [  1.    ,   0.    ,   0.    , 110.8833],
       [  3.    ,   0.    ,   0.    ,   7.775 ],
       [  3.    ,   0.    ,   0.    ,   7.55  ],
       [  3.    ,   1.    ,   0.    ,  17.8   ],
       [  3.    ,   0.    ,   0.    ,   8.4333],
       [  2.    ,   1.    ,   0.    ,  26.    ],
       [  2.    ,   0.    ,   0.    ,  13.    ],
       [  2.    ,   1.    ,   0.    ,  26.    ],
       [  3.    ,   0.    ,   5.    ,  29.125 ],
       [  2.    ,   1.    ,   1.    ,  32.5   ],
       [  2.    ,   0.    ,   0.    ,  13.    ],
       [  2.    ,   0.    ,   0.    ,  10.5   ],
       [  1.    ,   1.    ,   0.    , 146.5208],
       [  3.    ,   0.    ,   0.    ,   8.05  ],
       [  3.    ,   0.    ,   0.    ,   8.7125],
       [  3.    ,   0.    ,   0.    ,   7.4958],
       [  3.    ,   0.    ,   0.    ,   7.7958],
       [  3.    ,   1.    ,   0.    ,  24.15  ],
       [  3.    ,   0.    ,   0.    ,   8.05  ],
       [  3.    ,   0.    ,   0.    ,   7.05  ],
       [  3.    ,   0.    ,   0.    ,  56.4958],
       [  3.    ,   0.    ,   0.    ,   7.7875],
       [  2.    ,   1.    ,   0.    ,  26.    ],
       [  3.    ,   1.    ,   1.    ,  15.5   ],
       [  3.    ,   0.    ,   0.    ,   7.2292],
       [  1.    ,   0.    ,   0.    ,  26.55  ],
       [  2.    ,   0.    ,   0.    ,  13.    ],
       [  1.    ,   1.    ,   0.    ,  82.1708],
       [  3.    ,   0.    ,   0.    ,   8.4583],
       [  1.    ,   0.    ,   1.    ,  61.9792],
       [  2.    ,   0.    ,   0.    ,  10.5   ],
       [  1.    ,   1.    ,   0.    ,  51.8625],
       [  3.    ,   0.    ,   0.    ,   7.8958],
       [  3.    ,   0.    ,   0.    ,   7.05  ],
       [  1.    ,   0.    ,   1.    ,  63.3583],
       [  2.    ,   0.    ,   2.    ,  13.    ],
       [  1.    ,   0.    ,   0.    ,  26.3875],
       [  3.    ,   1.    ,   1.    ,  15.2458],
       [  3.    ,   0.    ,   0.    ,   7.125 ],
       [  3.    ,   0.    ,   0.    ,   7.225 ],
       [  3.    ,   1.    ,   5.    ,  31.3875],
       [  2.    ,   0.    ,   0.    ,  10.5   ],
       [  3.    ,   1.    ,   1.    ,  16.7   ]])

In [101]:
x_train_rem

array([[  1.    ,   0.    ,   0.    ,  28.5   ],
       [  2.    ,   0.    ,   0.    ,  13.    ],
       [  3.    ,   0.    ,   0.    ,   7.925 ],
       ...,
       [  3.    ,   2.    ,   0.    ,  14.1083],
       [  1.    ,   1.    ,   2.    , 120.    ],
       [  1.    ,   0.    ,   1.    ,  77.2875]], shape=(712, 4))

In [102]:
x_train_new = np.concatenate((x_train_rem,x_train_age,x_train_embarked,x_train_sex),axis = 1)

In [103]:
x_train_new.shape

(712, 8)

In [104]:
x_test_new = np.concatenate((x_test_rem,x_test_age,x_test_embarked,x_test_sex),axis=1)

In [105]:
x_test_new.shape

(179, 8)

In [106]:
# we combined all the important arrays 
# now we will train our model and predict the values from them
clf = DecisionTreeClassifier()
clf.fit(x_train_new,y_train)

DecisionTreeClassifier()

In [107]:
predicted = clf.predict(x_test_new)

In [108]:
predicted

array([0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1])

In [109]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,predicted)

0.7877094972067039

In [110]:
# we have created a model which has accuracy of 78.77 percentage 
# pickling the model 
import pickle

pickle.dump(ohe_embarked,open('Embarked.pkl','wb'))
pickle.dump(ohe_sex,open('Sex.pkl','wb'))
pickle.dump(clf,open('Model.pkl','wb'))