In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv('covid_toy.csv')

In [3]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [4]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [12]:
from sklearn.model_selection import train_test_split
x_train ,x_test,y_train ,y_test = train_test_split(df.drop(columns='has_covid'),df.iloc[:,[-1]],test_size=0.2,random_state=0)

In [18]:
# i will not apply the label encoder because we are learning the column transformer 
x_train.head()

    age  gender  fever   cough       city
43   22  Female   99.0    Mild  Bangalore
62   56  Female  104.0  Strong  Bangalore
3    31  Female   98.0    Mild    Kolkata
71   75  Female  104.0  Strong      Delhi
45   72    Male   99.0    Mild  Bangalore

# Using Column Transformer

In [28]:
from sklearn.compose import ColumnTransformer

transform = ColumnTransformer(transformers=[
    ('tr1',OneHotEncoder(sparse_output=False , drop='first'),['gender','city']),
    ('tr2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough'])
],remainder='passthrough')

In [30]:
transform.fit_transform(x_train).shape

(80, 7)

In [32]:
transform.transform(x_test).shape

(20, 7)

In [33]:
# Now we can see we did multiple transformations on single column 
# Column Transformer can make our work a lot easier when we are doing feature transformation