In [11]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt 
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score

In [34]:
df = pd.read_csv(r"C:\Skills\Machine Learning\ML main\Understanding Data\Titanic-Dataset.csv")

In [31]:
df.head()

   Survived  Pclass   Age  SibSp  Parch
0         0       3  22.0      1      0
1         1       1  38.0      1      0
2         1       3  26.0      0      0
3         1       1  35.0      1      0
4         0       3  35.0      0      0

In [8]:
df = df.dropna()

In [10]:
df.shape

(714, 5)

In [12]:
x=df.iloc[:,1:]
y=df['Survived']

In [19]:
cross_val_score(LogisticRegression(),x,y,cv=10).mean()

np.float64(0.6921165884194054)

# Feature Construction

In [20]:
# now making a new column family_size
x['Family_size'] = x['SibSp']+x['Parch']+1

In [23]:
x = x.drop(['SibSp','Parch'],axis=1)

In [30]:
# Now again applying cv score 
cross_val_score(LogisticRegression(),x,y,cv=6).mean()

np.float64(0.6988795518207284)

In [32]:
# you can see we slightly increase our accuracy

# Feature Spliting

In [35]:
# making new feature 
df.head()

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [65]:
df['Surname'] = df['Name'].str.split(', ',expand=True)[0]

In [57]:
df['title'] = df['Name'].str.split(', ',expand=True)[1].str.split('.',expand = True)[0]

In [59]:
df['name'] = df['Surname'] = df['Name'].str.split(', ',expand=True)[1].str.split('.',expand = True)[1]

In [66]:
df[['title','Surname','name']].head()

  title    Surname                                    name
0    Mr     Braund                             Owen Harris
1   Mrs    Cumings   John Bradley (Florence Briggs Thayer)
2  Miss  Heikkinen                                   Laina
3   Mrs   Futrelle           Jacques Heath (Lily May Peel)
4    Mr      Allen                           William Henry

In [69]:
# We splittted the names and created new features 
# we can try on a new data set 
df = pd.read_csv('Social_Network_Ads.csv')

In [70]:
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [71]:
df['Adult'] = np.where(df['Age']>=18,'Yes','No')

In [74]:
df['Taxable'] = np.where(df['EstimatedSalary']>100000,'Taxable','Not Taxable')

In [75]:
df['Taxable'].value_counts()

Taxable
Not Taxable    327
Taxable         73
Name: count, dtype: int64

In [ ]:
# we can create some features like that