In [1]:
import pandas as pd 
import numpy as np

In [2]:
time=pd.read_csv('messages.csv')
date=pd.read_csv('orders.csv')

In [4]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [5]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [7]:
# conveting to datattime 
date['date'] = pd.to_datetime(date['date'])
time['date'] = pd.to_datetime(time['date'])

In [8]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [9]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [26]:
# now we can extract multiple things from our column 
date['year'] = date['date'].dt.year
date['month'] = date['date'].dt.month
date['month_name'] = date['date'].dt.month_name()
date['day'] = date['date'].dt.day
date['day_of_week'] = date['date'].dt.day_of_week
date['day_name'] = date['date'].dt.day_name()

In [27]:
date.head()

,date,product_id,city_id,orders,year,month,month_name,day,day_of_week,day_name
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday

In [36]:
# now we can work on 
time['hour']=time['date'].dt.hour
time['second']=time['date'].dt.second
time['minute']=time['date'].dt.minute
time['time']=time['date'].dt.time

In [37]:
time.sample(5)

,date,msg,hour,second,minute,time
348,2015-03-15 00:38:00,ищу уникальную симпатичную девушку от 25лет ...,0,0,38,00:38:00
760,2013-08-17 01:17:00,м49 позн с ж для приятных в стреч/098 614 0 9 58/,1,0,17,01:17:00
544,2015-01-14 00:17:00,Андрюшка я люблю тебя больше всех! Ты удивите...,0,0,17,00:17:00
700,2015-12-25 23:02:00,м38 позн с жен для встреч 0676370548,23,0,2,23:02:00
295,2013-01-04 01:45:00,ПООБЩАЮСЬ С ДЕВУШКОЙ.063 413 86 95.ЗАДЕРЖИ. ...,1,0,45,01:45:00

In [43]:
import datetime
today = datetime.datetime.today()

In [45]:
today-time['date']

0     4575 days 12:31:48.416979
1     4439 days 13:41:48.416979
2     4925 days 13:00:48.416979
3     4227 days 12:50:48.416979
4     4624 days 14:10:48.416979
                 ...
995   5214 days 12:31:48.416979
996   4535 days 14:07:48.416979
997   5000 days 13:44:48.416979
998   5116 days 13:47:48.416979
999   4388 days 13:56:48.416979
Name: date, Length: 1000, dtype: timedelta64[ns]

In [ ]:
# we can get how many dates and times passed