In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt 
from sklearn.model_selection import train_test_split

In [4]:
df = pd.read_csv(r"C:\Skills\Machine Learning\ML main\Understanding Data\Titanic-Dataset.csv",usecols=['Age','Pclass','Fare','Survived'])

In [5]:
df.head()

   Survived  Pclass   Age     Fare
0         0       3  22.0   7.2500
1         1       1  38.0  71.2833
2         1       3  26.0   7.9250
3         1       1  35.0  53.1000
4         0       3  35.0   8.0500

In [8]:
from sklearn.impute import KNNImputer,SimpleImputer

In [7]:
# seeing how many percentage of missing values are there 
df.isnull().mean()

Survived    0.000000
Pclass      0.000000
Age         0.198653
Fare        0.000000
dtype: float64

In [9]:
# doing train test split 
# we will compare the performance of simple mean imputer and our knn imputer 
x_train , x_test , y_train , y_test = train_test_split(df.iloc[:,1:],df['Survived'],test_size=0.25,random_state=25)

In [10]:
x_train.head()

     Pclass   Age    Fare
161       2  40.0  15.750
776       3   NaN   7.750
280       3  65.0   7.750
276       3  45.0   7.750
598       3   NaN   7.225

In [136]:
# applying the knn imputer 

knn = KNNImputer(n_neighbors=5,weights='uniform')

x_train_trf = knn.fit_transform(x_train)
x_test_trf = knn.transform(x_test)

In [137]:
from sklearn.linear_model import LogisticRegression

In [149]:
lr = LogisticRegression()

lr.fit(x_train_trf,y_train)
pred = lr.predict(x_test_trf)

In [150]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,pred)

0.7130044843049327

In [151]:
# as you can see we got a accuracy of 71 
# chekcing for Simple imputer 
si = SimpleImputer(strategy='most_frequent')
x_train_trf2 = si.fit_transform(x_train)
x_test_trf2 = si.transform(x_test)

lr2 = LogisticRegression()

lr2.fit(x_train_trf2,y_train)
pred2 = lr2.predict(x_test_trf2)

In [152]:
accuracy_score(y_test,pred2)

0.7219730941704036