In [1]:
import pandas as pd
import requests

In [3]:
# i am fething genres of movies from API of watchmode.com 
data = requests.get('https://api.watchmode.com/v1/genres/?apiKey=Gv6A5xOxZcjI21EhKaMBGTTrMK20IyhevxHASHlS')
type(data)

requests.models.Response

In [4]:
data = data.json()

In [5]:
pd.DataFrame(data)
#  i only want name of the generes so what i can do is 
genre = pd.DataFrame(data)[['name']]
genre

                  name
0               Action
1   Action & Adventure
2                Adult
3            Adventure
4            Animation
5                Anime
6            Biography
7               Comedy
8                Crime
9          Documentary
10               Drama
11              Family
12             Fantasy
13                Food
14           Game Show
15             History
16              Horror
17                Kids
18               Music
19             Musical
20             Mystery
21              Nature
22                News
23             Reality
24             Romance
25    Sci-Fi & Fantasy
26     Science Fiction
27                Soap
28              Sports
29        Supernatural
30                Talk
31            Thriller
32              Travel
33            TV Movie
34                 War
35      War & Politics
36             Western

In [6]:
# now exapmle i need data of bradd pitt from that api 
brad = requests.get('https://api.watchmode.com/v1/person/7110004?apiKey=Gv6A5xOxZcjI21EhKaMBGTTrMK20IyhevxHASHlS')

In [7]:
df = pd.DataFrame(brad.json())

In [8]:
df

,id,full_name,first_name,last_name,tmdb_id,imdb_id,main_profession,secondary_profession,tertiary_profession,date_of_birth,date_of_death,place_of_birth,gender,known_for,relevance_percentile
0,7110004,Brad Pitt,Brad,Pitt,287,nm0000093,actor,soundtrack,producer,1963-12-18,None,"Shawnee, Oklahoma, USA",m,1132806,100
1,7110004,Brad Pitt,Brad,Pitt,287,nm0000093,actor,soundtrack,producer,1963-12-18,None,"Shawnee, Oklahoma, USA",m,1183315,100
2,7110004,Brad Pitt,Brad,Pitt,287,nm0000093,actor,soundtrack,producer,1963-12-18,None,"Shawnee, Oklahoma, USA",m,1336708,100
3,7110004,Brad Pitt,Brad,Pitt,287,nm0000093,actor,soundtrack,producer,1963-12-18,None,"Shawnee, Oklahoma, USA",m,1387087,100

In [12]:
# i got info about him 
# now i want to fetch titles from the api
titles = requests.get('https://api.watchmode.com/v1/list-titles/?apiKey=Gv6A5xOxZcjI21EhKaMBGTTrMK20IyhevxHASHlS')
pd.DataFrame(titles.json()['titles'])

,id,title,year,imdb_id,tmdb_id,tmdb_type,type
0,3250797,Rafa,2026,tt35052852,279884,tv,tv_miniseries
1,3174840,Clarkson's Farm,2021,tt10541088,117648,tv,tv_series
2,3178664,The Legend of Vox Machina,2022,tt11247158,135934,tv,tv_series
3,3224329,Murder Mindfully,2024,tt30217222,252372,tv,tv_series
4,3169127,Sweet Magnolias,2020,tt9077540,102904,tv,tv_series
...,...,...,...,...,...,...,...
245,544066,Agatha All Along,2024,tt15571732,138501,tv,tv_miniseries
246,3239271,The Other Bennet Sister,2026,tt37022512,273866,tv,tv_series
247,3225800,When the Phone Rings,2024,tt33503491,253905,tv,tv_series
248,3220779,Stick,2025,tt31710249,248830,tv,tv_series
249,3212158,Dandadan,2024,tt30217403,240411,tv,tv_series

# Fetching data from a new api url

In [38]:
url = "https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/40381/hscard"

headers = {
	"x-rapidapi-key": "bdca34d3d6mshd37bc0156f99f2dp1e81aajsnc53c2acd03a9",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com",
	"Content-Type": "application/json"
}

response = requests.get(url, headers=headers)

response = (response.json()['scorecard'])
pd.DataFrame(response)

,inningsid,batsman,bowler,fow,extras,score,wickets,overs,runrate,batteamname,batteamsname,isdeclared,isfollowon,ballnbr,rpb,partnership
0,1,"[{'id': 1114, 'balls': 5, 'runs': 5, 'fours': ...","[{'id': 15475, 'overs': '4', 'maidens': 0, 'wi...","{'fow': [{'batsmanid': 1114, 'batsmanname': 'S...","{'legbyes': 1, 'byes': 0, 'wides': 5, 'noballs...",150,10,18.5,7.96,Ireland,IRE,False,False,113,1.33,"{'partnership': [{'id': 0, 'bat1id': 1114, 'ba..."
1,2,"[{'id': 22891, 'balls': 23, 'runs': 16, 'fours...","[{'id': 10449, 'overs': '4', 'maidens': 0, 'wi...","{'fow': [{'batsmanid': 22896, 'batsmanname': '...","{'legbyes': 4, 'byes': 1, 'wides': 6, 'noballs...",141,7,20.0,7.05,United States,USA,False,False,120,1.18,"{'partnership': [{'id': 0, 'bat1id': 22891, 'b..."

# Another API just for practice Student Data

In [39]:
response = requests.get('https://dummyjson.com/users')

In [43]:
pd.DataFrame(response.json()['users'])

,id,firstName,lastName,maidenName,age,gender,email,phone,username,password,...,address,macAddress,university,bank,company,ein,ssn,userAgent,crypto,role
0,1,Emily,Johnson,Smith,29,female,emily.johnson@x.dummyjson.com,+81 965-431-3024,emilys,emilyspass,...,"{'address': '626 Main Street', 'city': 'Phoeni...",47:fa:41:18:ec:eb,University of Wisconsin--Madison,"{'cardExpire': '05/28', 'cardNumber': '3693233...","{'department': 'Engineering', 'name': 'Dooley,...",977-175,900-590-289,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",admin
1,2,Michael,Williams,,36,male,michael.williams@x.dummyjson.com,+49 258-627-6644,michaelw,michaelwpass,...,"{'address': '385 Fifth Street', 'city': 'Houst...",79:15:78:99:60:aa,Ohio State University,"{'cardExpire': '01/30', 'cardNumber': '3530633...","{'department': 'Support', 'name': 'Spinka - Di...",912-602,108-953-962,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",admin
2,3,Sophia,Brown,,43,female,sophia.brown@x.dummyjson.com,+81 210-652-2785,sophiab,sophiabpass,...,"{'address': '1642 Ninth Street', 'city': 'Wash...",12:a3:d3:6f:5c:5b,Pepperdine University,"{'cardExpire': '10/27', 'cardNumber': '6011212...","{'department': 'Research and Development', 'na...",963-113,638-461-822,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",admin
3,4,James,Davis,,46,male,james.davis@x.dummyjson.com,+49 614-958-9364,jamesd,jamesdpass,...,"{'address': '238 Jefferson Street', 'city': 'S...",10:7d:df:1f:97:58,University of Southern California,"{'cardExpire': '07/30', 'cardNumber': '5303440...","{'department': 'Support', 'name': 'Pagac and S...",904-810,116-951-314,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",admin
4,5,Emma,Miller,Johnson,31,female,emma.miller@x.dummyjson.com,+91 759-776-1614,emmaj,emmajpass,...,"{'address': '607 Fourth Street', 'city': 'Jack...",32:b9:7e:8d:f5:e8,Northeastern University,"{'cardExpire': '07/30', 'cardNumber': '5237188...","{'department': 'Human Resources', 'name': 'Gra...",403-505,526-210-885,Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:9...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",admin
5,6,Olivia,Wilson,,23,female,olivia.wilson@x.dummyjson.com,+91 607-295-6448,oliviaw,oliviawpass,...,"{'address': '547 First Street', 'city': 'Fort ...",9c:7f:ea:34:18:19,University of North Carolina--Chapel Hill,"{'cardExpire': '06/30', 'cardNumber': '3763200...","{'department': 'Product Management', 'name': '...",921-709,836-772-168,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",moderator
6,7,Alexander,Jones,,39,male,alexander.jones@x.dummyjson.com,+61 260-824-4986,alexanderj,alexanderjpass,...,"{'address': '664 Maple Street', 'city': 'India...",d2:64:58:2d:1c:46,University of Illinois--Urbana-Champaign,"{'cardExpire': '12/29', 'cardNumber': '5189302...","{'department': 'Engineering', 'name': 'Dickens...",638-127,722-993-925,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",moderator
7,8,Ava,Taylor,,28,female,ava.taylor@x.dummyjson.com,+1 458-853-7877,avat,avatpass,...,"{'address': '1197 First Street', 'city': 'Fort...",8d:2e:c2:d6:e7:a8,University of Wisconsin--Madison,"{'cardExpire': '08/30', 'cardNumber': '5349974...","{'department': 'Marketing', 'name': 'Nikolaus ...",297-762,257-419-109,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",moderator
8,9,Ethan,Martinez,,34,male,ethan.martinez@x.dummyjson.com,+92 933-608-5081,ethanm,ethanmpass,...,"{'address': '466 Pine Street', 'city': 'San An...",59:e:9e:e3:29:da,Syracuse University,"{'cardExpire': '10/27', 'cardNumber': '3598603...","{'department': 'Support', 'name': 'Gorczany - ...",790-434,569-650-348,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",moderator
9,10,Isabella,Anderson,Davis,32,female,isabella.anderson@x.dummyjson.com,+49 770-658-4885,isabellad,isabelladpass,...,"{'address': '1964 Oak Street', 'city': 'New Yo...",b1:b0:d0:a2:82:80,California Institute of Technology (Caltech),"{'cardExpire': '03/30', 'cardNumber': '3602093...","{'department': 'Marketing', 'name': 'Pollich -...",127-297,902-438-728,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",moderator
10,11,Liam,Garcia,,30,male,liam.garcia@x.dummyjson.com,+92 870-217-6201,liamg,liamgpass,...,"{'address': '576 Fifth Street', 'city': 'Denve...",31:9a:28:8b:99:6c,Ohio State University,"{'cardExpire': '12/29', 'cardNumber': '3614993...","{'department': 'Services', 'name': 'Considine ...",326-604,933-784-949,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",moderator
11,12,Mia,Rodriguez,,25,female,mia.rodriguez@x.dummyjson.com,+49 989-461-8403,miar,miarpass,...,"{'address': '1627 Sixth Street', 'city': 'Jack...",53:d7:a4:6:1e:58,William & Mary,"{'cardExpire': '02/29', 'cardNumber': '3439323...","{'department': 'Accounting', 'name': 'Miller, ...",754-660,749-524-124,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",moderator
12,13,Noah,Hernandez,,41,male,noah.hernandez@x.dummyjson.com,+49 393-605-6968,noahh,noahhpass,...,"{'address': '1413 Maple Street', 'city': 'New ...",d4:fe:ae:8f:eb:a3,New York University (NYU),"{'cardExpire': '03/30', 'cardNumber': '6262462...","{'department': 'Engineering', 'name': 'Botsfor...",877-628,660-847-389,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",moderator
13,14,Charlotte,Lopez,Martinez,37,female,charlotte.lopez@x.dummyjson.com,+44 373-953-5028,charlottem,charlottempass,...,"{'address': '208 Second Street', 'city': 'Colu...",f6:ff:37:aa:6c:f1,Northeastern University,"{'cardExpire': '12/27', 'cardNumber': '3634388...","{'department': 'Accounting', 'name': 'Zulauf a...",364-782,255-491-479,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",moderator
14,15,William,Gonzalez,,33,male,william.gonzalez@x.dummyjson.com,+81 905-252-7319,williamg,williamgpass,...,"{'address': '31 Maple Street', 'city': 'San Jo...",f5:68:28:f9:ec:89,Tufts University,"{'cardExpire': '05/30', 'cardNumber': '6228256...","{'department': 'Marketing', 'name': 'Spinka - ...",830-515,690-544-755,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",moderator
15,16,Avery,Perez,,26,female,avery.perez@x.dummyjson.com,+61 731-431-3457,averyp,averyppass,...,"{'address': '1125 First Street', 'city': 'Colu...",b3:ff:f3:c5:37:46,Harvard University,"{'cardExpire': '08/29', 'cardNumber': '3780240...","{'department': 'Accounting', 'name': 'Herzog I...",348-493,679-523-686,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",user
16,17,Evelyn,Sanchez,,38,female,evelyn.sanchez@x.dummyjson.com,+1 623-880-6871,evelyns,evelynspass,...,"{'address': '1170 Lincoln Street', 'city': 'Sa...",f8:e5:bd:43:bc:d8,Washington University in St. Louis,"{'cardExpire': '01/29', 'cardNumber': '3514443...","{'department': 'Support', 'name': 'Predovic - ...",604-817,689-332-644,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",user
17,18,Logan,Torres,,32,male,logan.torres@x.dummyjson.com,+81 507-434-8733,logant,logantpass,...,"{'address': '907 Seventh Street', 'city': 'Col...",40:d:5c:1:7d:bf,University of Illinois--Urbana-Champaign,"{'cardExpire': '04/30', 'cardNumber': '6258651...","{'department': 'Training', 'name': 'Jast - Nad...",576-218,806-639-934,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",user
18,19,Abigail,Rivera,,29,female,abigail.rivera@x.dummyjson.com,+91 228-363-7806,abigailr,abigailrpass,...,"{'address': '996 Oak Street', 'city': 'Chicago...",1d:a6:58:2a:e5:e4,California Institute of Technology (Caltech),"{'cardExpire': '01/27', 'cardNumber': '6011399...","{'department': 'Human Resources', 'name': 'Pro...",173-637,655-823-929,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",user
19,20,Jackson,Evans,,35,male,jackson.evans@x.dummyjson.com,+44 468-628-6686,jacksone,jacksonepass,...,"{'address': '1873 Main Street', 'city': 'New Y...",81:14:1:97:88:85,Ohio State University,"{'cardExpire': '07/30', 'cardNumber': '3767606...","{'department': 'Legal', 'name': 'Kuhlman LLC',...",843-260,248-787-886,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",user
20,21,Madison,Collins,,27,female,madison.collins@x.dummyjson.com,+81 259-957-5711,madisonc,madisoncpass,...,"{'address': '1892 Lincoln Street', 'city': 'Ph...",13:b0:d0:23:4d:26,University of Pennsylvania,"{'cardExpire': '09/27', 'cardNumber': '5551259...","{'department': 'Engineering', 'name': 'Mayer -...",716-166,457-258-950,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",user
21,22,Elijah,Stewart,,34,male,elijah.stewart@x.dummyjson.com,+44 468-357-7872,elijahs,elijahspass,...,"{'address': '1701 Eighth Street', 'city': 'Col...",75:17:c6:35:fc:6d,Georgetown University,"{'cardExpire': '05/28', 'cardNumber': '3648138...","{'department': 'Legal', 'name': 'Langworth Gro...",520-394,287-380-801,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",user
22,23,Chloe,Morales,,40,female,chloe.morales@x.dummyjson.com,+92 468-541-7133,chloem,chloempass,...,"{'address': '401 Fourth Street', 'city': 'Dall...",fc:f:29:e1:37:b8,Syracuse University,"{'cardExpire': '09/30', 'cardNumber': '3470362...","{'department': 'Sales', 'name': 'Grady LLC', '...",913-597,938-883-163,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",user
23,24,Mateo,Nguyen,,31,male,mateo.nguyen@x.dummyjson.com,+1 341-597-6694,mateon,mateonpass,...,"{'address': '1578 Fourth Street', 'city': 'Col...",a7:26:10:7a:36:29,Columbia University,"{'cardExpire': '12/29', 'cardNumber': '4021840...","{'department': 'Accounting', 'name': 'Spinka L...",229-249,416-877-230,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",user
24,25,Harper,Kelly,Evans,28,female,harper.kelly@x.dummyjson.com,+92 518-863-2863,harpere,harperepass,...,"{'address': '1591 Adams Street', 'city': 'Phil...",b:ff:33:67:94:e4,Boston College,"{'cardExpire': '06/27', 'cardNumber': '4488823...","{'department': 'Legal', 'name': 'Leffler, Rolf...",592-557,209-544-548,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",user
25,26,Evelyn,Gonzalez,,36,female,evelyn.gonzalez@x.dummyjson.com,+61 708-508-4638,evelyng,evelyngpass,...,"{'address': '1065 Lincoln Street', 'city': 'Da...",89:5e:5a:2a:72:42,Washington University in St. Louis,"{'cardExpire': '08/28', 'cardNumber': '6011735...","{'department': 'Accounting', 'name': 'Tromp, G...",569-275,487-680-127,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",user
26,27,Daniel,Cook,,42,male,daniel.cook@x.dummyjson.com,+44 254-761-6843,danielc,danielcpass,...,"{'address': '1163 Pine Street', 'city': 'Los A...",6e:73:dc:3a:85:10,Columbia University,"{'cardExpire': '05/29', 'cardNumber': '5485409...","{'department': 'Support', 'name': 'Morissette,...",585-905,645-515-583,Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:9...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",user
27,28,Lily,Lee,Brown,30,female,lily.lee@x.dummyjson.com,+1 808-757-9867,lilyb,lilybpass,...,"{'address': '1946 Oak Street', 'city': 'Phoeni...",18:b6:c7:a:50:3f,Johns Hopkins University,"{'cardExpire': '12/28', 'cardNumber': '5551782...","{'department': 'Product Management', 'name': '...",229-776,358-185-671,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",user
28,29,Henry,Hill,,39,male,henry.hill@x.dummyjson.com,+1 240-833-4680,henryh,henryhpass,...,"{'address': '1837 Maple Street', 'city': 'Indi...",fa:c3:1b:21:5f:44,University of Illinois--Urbana-Champaign,"{'cardExpire': '11/29', 'cardNumber': '3625097...","{'department': 'Services', 'name': 'Gerlach, F...",118-957,925-686-100,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",user
29,30,Addison,Wright,,33,female,addison.wright@x.dummyjson.com,+1 514-384-3300,addisonw,addisonwpass,...,"{'address': '568 Tenth Street', 'city': 'San F...",fb:0:94:21:16:c,Syracuse University,"{'cardExpire': '06/28', 'cardNumber': '5274971...","{'department': 'Services', 'name': 'Kreiger In...",415-286,804-492-390,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",user

In [ ]:
# this is just to get some real world data because when we will be going to make projects then real world data is very important