In [1]:
# importing libraires 
import pandas as pd

# Working wiht JSON

In [7]:
# to read json file(locally)
pd.read_json('train.json').head(2)

      id      cuisine                                        ingredients
0  10259        greek  [romaine lettuce, black olives, grape tomatoes...
1  25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...

In [8]:
# to get data from a json url 
pd.read_json('https://jsonplaceholder.typicode.com/users').head(2)

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."

# Working with SQL

In [14]:
# we have to install mysql.connector to connect database with the python code 
!pip install mysql.connector

Requirement already satisfied: mysql.connector in C:\Users\singl\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.2.9)

In [15]:
import mysql.connector

In [ ]:
# conn = mysql.connector.connect(
#     host="localhost",
#     user="root",
#     password="your_password",
#     database="your_database"
# )

# this is used to connect to the database but i have not created any database so it will not run